# Generated by Django 5.2.1 on 2025-05-15 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athleteprofile',
            name='age',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='athleteprofile',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='athleteprofile',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='athleteprofile',
            name='height',
            field=models.FloatField(blank=True, default=None, help_text='Em metros', null=True),
        ),
        migrations.AlterField(
            model_name='athleteprofile',
            name='position',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='athleteprofile',
            name='video_link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='athleteprofile',
            name='weight',
            field=models.FloatField(blank=True, default=None, help_text='Em kg', null=True),
        ),
        migrations.CreateModel(
            name='VideoPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('video_url', models.URLField(help_text='URL do YouTube ou Vimeo')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='video_thumbnails/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
