# Generated by Django 5.2.1 on 2025-05-26 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_athleteprofile_age_alter_athleteprofile_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='athleteprofile',
            name='desired_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salário Desejado (USD)'),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='needs_food',
            field=models.BooleanField(default=False, verbose_name='Precisa de Alimentação'),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='needs_housing',
            field=models.BooleanField(default=False, verbose_name='Precisa de Moradia'),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='needs_transport',
            field=models.BooleanField(default=False, verbose_name='Precisa de Transporte'),
        ),
        migrations.CreateModel(
            name='ClubProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('founded_year', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='club_logos/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='club_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
