# Generated by Django 5.2.1 on 2025-05-27 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_athleteprofile_desired_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athleteprofile',
            name='needs_food',
            field=models.CharField(choices=[('none', 'Não necessário'), ('partial', 'Parcial'), ('full', 'Completa')], default='none', max_length=10, verbose_name='Alimentação'),
        ),
        migrations.AlterField(
            model_name='athleteprofile',
            name='needs_housing',
            field=models.CharField(choices=[('none', 'Não necessário'), ('shared', 'Compartilhada'), ('private', 'Privativa')], default='none', max_length=10, verbose_name='Moradia'),
        ),
        migrations.AlterField(
            model_name='athleteprofile',
            name='needs_transport',
            field=models.CharField(choices=[('none', 'Não necessário'), ('local', 'Local'), ('full', 'Completo')], default='none', max_length=10, verbose_name='Transporte'),
        ),
    ]
