# Generated by Django 5.2.1 on 2025-06-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_athleteprofile_needs_food_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='athleteprofile',
            name='team',
            field=models.CharField(choices=[('Rondonopolis Hawks', 'Hawks'), ('Cuiabá Arsenal', 'Arsenal'), ('Sinop Coyotes', 'Coyotes'), ('Galo', 'Galo'), ('Remo', 'Remo')], default='Rondonopolis Hawks', max_length=100),
        ),
    ]
